### ISSUE TITLE
Internal server error (500) when accessing empty note

### ISSUE THREAD

**Issue by Bartcardi** [xeust/yarc#11]
When I click on `edit` to change the text of a note, clear everything and save it then this results in a 500 response when accessing it. Here is the final trace of the logs.

```
pydantic.error_wrappers.ValidationError: 1 validation error for Note
content
  none is not an allowed value (type=type_error.none.not_allowed)
``` 

_Edit:_ I found out how to delete an empty note using the deta run cli: `deta run del -- --name :note_name`

**Comment by xeust** [comment]
Thanks for reporting this.

Turns out this is a db issue where empty strings are stored as `null`. I have forwarded this issue to the db team.

Nonetheless, I have pushed an update that should fix this issue. 

Lines 58-59 on `main.py`:

```
if not note_dict["content"]: 
        note_dict["content"] = ""
```
