### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by kauderk** [xeust/yarc#26]
I'm lost. I managed to deploy to **deta**, but I don't know what's wrong with my setup.
I didn't touch anything, yet I get this error. BTW I'm a windows user.

I can't provide more context. The server and deta's logs just output "Internal Server Error".

![image](https://user-images.githubusercontent.com/65237382/202244599-36ea8e9f-3ac9-4592-accd-24f8a5eefc22.png)

"/notes/:note_name?json=true" is the way to "GET" notes, right?
Do we have to "PUT" something in order for the server to have something to work with?

**Comment by salaivv** [comment]
I am facing issue as well.
