### ISSUE TITLE
Doesn't save

### ISSUE THREAD

**Issue by justinmoon** [xeust/yarc#8]
I got this running this in Deta (cool platform, TIL), but it doesn't save.

I would click "edit", change the note and then click "save". But if I revisited the not it would just display the default:

![image](https://user-images.githubusercontent.com/4335621/89448115-bab98d00-d71c-11ea-9b47-cfe91f16b2f3.png)

Do I need to configure a database or something?

**Comment by abdelhai** [comment]
Are you getting any error? @justinmoon

**Comment by justinmoon** [comment]
No. The `PUT` to save the note returns a `200` as well ...

**Comment by justinmoon** [comment]
https://jas6gm.deta.dev

**Comment by abdelhai** [comment]
I can't access because Access protection is on. Open for a quick call? We can sort it out quickly. @justinmoon

**Comment by xeust** [comment]
@justinmoon I can't replicate the error, but also happy to do a video chat if you want to show me what's going on

**Comment by justinmoon** [comment]
Huh I tried again and saving works.
