### ISSUE TITLE
Does this support nested directories for the files?

### ISSUE THREAD

**Issue by NightMachinery** [xeust/yarc#9]

**Comment by xeust** [comment]
As of now file names must be a string, while directories and slashes are not supported.

How do you image your use case?

You want your notes in nested directories i.e.: `some_dir/other_dir/note`

**Comment by NightMachinery** [comment]
[**@xeust**](https://github.com/xeust) commented on [Aug 6, 2020, 11:59 PM GMT+4:30](https://github.com/xeust/yarc/issues/9#issuecomment-670149632 "2020-08-06T19:29:42Z - Replied by Github Reply Comments"):
> As of now file names must be a string, while directories and slashes are not supported.
> 
> How do you image your use case?
> 
> You want your notes in nested directories i.e.: `some_dir/other_dir/note`

Sorry, I think that I need to do some more tinkering with my setup before I know what exactly I need. So I'll close this issue.

But to not let the question remain unanswered, I already have my notes in highly nested directories:

![image](https://user-images.githubusercontent.com/36224762/89577770-67dbf480-d846-11ea-8ce3-62d9f208209c.png)


My primary problems with my current setup are the lack of backlinks, and a lack of web UI. I am going to learn org-mode, and see what I can do from there ...

**Comment by xeust** [comment]
Yeah this is interesting, thanks for sharing.

The current structure is entirely free / hyperlink based without any hierarchy.

But there are two limitations in my mind:

1. Sometimes hierarchy / structure is good
2. All notes are in a single namespace

**Comment by xeust** [comment]
Hi @NightMachinary ,

I'm still working on this -- any change you'd be up for a short interview / survey about your note taking in effort to improve yarc going forwards?
